# Generated by Django 2.0.4 on 2019-04-16 22:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0005_auto_20190416_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('CASH', '现金'), ('BANK', '银行'), ('WECHAT', '微信'), ('ALIPAY', '支付宝'), ('CHECK', '支票'), ('OTHER', '其他')], default='BANK', max_length=255, verbose_name='账户类型')),
                ('account_name', models.CharField(max_length=255, verbose_name='开户账号')),
                ('account_bank', models.CharField(max_length=255, verbose_name='开户银行')),
                ('account_user', models.CharField(max_length=255, verbose_name='开户名')),
                ('trades_num', models.IntegerField(default=0, verbose_name='交易次数')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('state', models.CharField(choices=[('DRAFT', '草稿'), ('APPROVE', '待审核'), ('DONE', '完成')], default='DRAFT', max_length=255, verbose_name='状态')),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Company', verbose_name='所属公司')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Partner', verbose_name='所属客户')),
            ],
            options={
                'db_table': 'account_account_bank',
                'ordering': ['-account_bank'],
            },
        ),
    ]
