# Generated by Django 2.0.4 on 2019-04-26 19:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_auto_20190426_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=255, verbose_name='账户简称')),
                ('account_type', models.CharField(choices=[('bank', '银行账户'), ('wechat', '微信'), ('alipay', '支付宝'), ('cash', '现金')], default='bank', max_length=255, verbose_name='账户类型')),
                ('usage_type', models.CharField(choices=[('partner', '客户'), ('employee', '员工')], default='partner', max_length=255, verbose_name='使用类型')),
                ('account_name', models.CharField(max_length=255, verbose_name='开户名')),
                ('account_bank', models.CharField(max_length=255, verbose_name='开户银行')),
                ('account_card', models.CharField(max_length=255, verbose_name='开户卡号')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True)),
                ('belongs_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_belongs_user', to=settings.AUTH_USER_MODEL, verbose_name='所属员工')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Company', verbose_name='所属公司')),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_create_user', to=settings.AUTH_USER_MODEL, verbose_name='创建用户')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Partner', verbose_name='归属客户')),
            ],
            options={
                'ordering': ['account_card'],
            },
        ),
    ]
