# Generated by Django 2.0.4 on 2019-04-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountaccount',
            name='short_name',
            field=models.CharField(default='', max_length=255, verbose_name='账户别名'),
        ),
    ]
