# Generated by Django 2.0.4 on 2019-05-01 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190428_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountaccount',
            name='create_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account_create_user', to=settings.AUTH_USER_MODEL, verbose_name='创建用户'),
        ),
        migrations.AlterField(
            model_name='accountaccount',
            name='usage_type',
            field=models.CharField(choices=[('external', '客户'), ('internal', '内部适用')], default='partner', max_length=255, verbose_name='使用类型'),
        ),
    ]
