# Generated by Django 2.0.4 on 2019-04-28 17:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_type', models.CharField(choices=[('supplier', '供应商'), ('internal', '内部位置'), ('customer', '客户位置'), ('return', '退回(作废)位置'), ('virtual', '虚拟位置'), ('production', '生产位置')], default='internal', max_length=255, verbose_name='位置类型')),
                ('name', models.CharField(max_length=255, verbose_name='仓库位置名称')),
                ('short_name', models.CharField(default='', max_length=255, verbose_name='简称')),
                ('code', models.CharField(default='', max_length=255, verbose_name='代号')),
                ('description', models.CharField(default='', max_length=255, verbose_name='描述')),
                ('posx', models.CharField(default='', max_length=255, verbose_name='X')),
                ('posy', models.CharField(default='', max_length=255, verbose_name='Y')),
                ('posz', models.CharField(default='', max_length=255, verbose_name='Z')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_location', to='base.Company', verbose_name='所属公司')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockWarehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='仓库名称')),
                ('short_name', models.CharField(default='', max_length=255, verbose_name='简称')),
                ('code', models.CharField(default='', max_length=255, verbose_name='代号')),
                ('description', models.CharField(default='', max_length=255, verbose_name='描述')),
                ('address', models.CharField(default='', max_length=255, verbose_name='详细地址')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.BaseCity', verbose_name='所在城市')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_warehouse', to='base.Company', verbose_name='所属公司')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Province', verbose_name='所在省份')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
