# Generated by Django 2.0.4 on 2019-04-19 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockpickingtype',
            name='diff_type',
        ),
    ]
