# Generated by Django 2.0.4 on 2019-04-19 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20190418_1652'),
        ('stock', '0002_remove_stockpickingtype_diff_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklocation',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Company', verbose_name='所在公司'),
        ),
        migrations.AlterField(
            model_name='stocklocation',
            name='name',
            field=models.CharField(max_length=255, verbose_name='位置名称'),
        ),
    ]
