# Generated by Django 2.0.4 on 2019-04-14 22:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_stocklocation_create_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'stock_move',
            },
        ),
        migrations.CreateModel(
            name='StockMoveLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'stock_move_line',
            },
        ),
        migrations.CreateModel(
            name='StockPicking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'stock_picking',
            },
        ),
        migrations.CreateModel(
            name='StockPickingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='作业类型')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='唯一编码')),
                ('short_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='简称')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='仓库位置地址')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'stock_picking_type',
            },
        ),
        migrations.CreateModel(
            name='StockProductionLot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'stock_production_lot',
            },
        ),
        migrations.CreateModel(
            name='StockQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'stock_quant',
            },
        ),
        migrations.AlterField(
            model_name='stocklocation',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='仓库名称'),
        ),
        migrations.AlterField(
            model_name='stockwarehouse',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='仓库名称'),
        ),
        migrations.AddField(
            model_name='stockpickingtype',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.StockWarehouse', verbose_name='所属仓库'),
        ),
    ]
