# Generated by Django 2.0.4 on 2019-04-14 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_basesequence'),
        ('stock', '0003_auto_20190414_2212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockpickingtype',
            options={'ordering': ['-name']},
        ),
        migrations.AddField(
            model_name='stockpickingtype',
            name='default_destination_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_locations', to='stock.StockLocation', verbose_name='默认目的位置'),
        ),
        migrations.AddField(
            model_name='stockpickingtype',
            name='default_source_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_locations', to='stock.StockLocation', verbose_name='默认来源位置'),
        ),
        migrations.AddField(
            model_name='stockpickingtype',
            name='op_type',
            field=models.CharField(choices=[('INBOUND', '供应商'), ('OUTBOUND', '客户'), ('INTERNAL', '内部')], default='INTERNAL', max_length=255, verbose_name='出入类型'),
        ),
        migrations.AddField(
            model_name='stockpickingtype',
            name='return_picking_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.StockPickingType', verbose_name='退回的作业类型'),
        ),
        migrations.AddField(
            model_name='stockpickingtype',
            name='sequence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.BaseSequence', verbose_name='序列号'),
        ),
        migrations.AddField(
            model_name='stockpickingtype',
            name='show_reserved',
            field=models.BooleanField(default=False, verbose_name='显示预留'),
        ),
        migrations.AddField(
            model_name='stockpickingtype',
            name='use_already_lot',
            field=models.BooleanField(default=False, verbose_name='是否使用已有的批次号'),
        ),
        migrations.AddField(
            model_name='stockpickingtype',
            name='use_new_lot',
            field=models.BooleanField(default=False, verbose_name='是否创建新的批次号'),
        ),
    ]
