# Generated by Django 2.0.4 on 2019-04-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20190419_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklocation',
            name='pos_x',
            field=models.CharField(max_length=255, verbose_name='X'),
        ),
        migrations.AlterField(
            model_name='stocklocation',
            name='pos_y',
            field=models.CharField(max_length=255, verbose_name='Y'),
        ),
        migrations.AlterField(
            model_name='stocklocation',
            name='pos_z',
            field=models.CharField(max_length=255, verbose_name='Z'),
        ),
        migrations.AlterUniqueTogether(
            name='stocklocation',
            unique_together={('pos_x', 'pos_y', 'pos_z')},
        ),
    ]
