# Generated by Django 2.0.4 on 2019-04-14 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_basesequence'),
        ('stock', '0004_auto_20190414_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockpicking',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Company', verbose_name='所在公司'),
        ),
        migrations.AddField(
            model_name='stockpicking',
            name='destination_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_locations', to='stock.StockLocation', verbose_name='目的位置'),
        ),
        migrations.AddField(
            model_name='stockpicking',
            name='name',
            field=models.CharField(default='stock_picking', max_length=255, unique=True, verbose_name='库存调拨单号'),
        ),
        migrations.AddField(
            model_name='stockpicking',
            name='origin',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='源单据号'),
        ),
        migrations.AddField(
            model_name='stockpicking',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Partner', verbose_name='合作伙伴'),
        ),
        migrations.AddField(
            model_name='stockpicking',
            name='source_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_locations', to='stock.StockLocation', verbose_name='来源位置'),
        ),
        migrations.AddField(
            model_name='stockpickingtype',
            name='diff_type',
            field=models.CharField(choices=[('PFU', '总公司从供应商收货'), ('PTC', '总公司对子公司发货'), ('PTU', '总公司对客户发货'), ('PRU', '总公司对供应商退货'), ('CFP', '子公司从总公司收货'), ('CFU', '子公司从供应商收货'), ('CTU', '子公司对客户发货'), ('CRU', '子公司对供应商退货'), ('CRP', '子公司对总公司退货'), ('URP', '客户对总公司退货'), ('URC', '客户对子公司退货')], default='CFP', max_length=255, verbose_name='区分作业类型'),
        ),
        migrations.AlterField(
            model_name='stockpickingtype',
            name='default_destination_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_destination_locations', to='stock.StockLocation', verbose_name='默认目的位置'),
        ),
        migrations.AlterField(
            model_name='stockpickingtype',
            name='default_source_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_source_locations', to='stock.StockLocation', verbose_name='默认来源位置'),
        ),
        migrations.AlterField(
            model_name='stockpickingtype',
            name='op_type',
            field=models.CharField(choices=[('INBOUND', '供应商'), ('OUTBOUND', '客户'), ('INTERNAL', '内部')], default='INTERNAL', max_length=255, verbose_name='出入站类型'),
        ),
    ]
