# Generated by Django 2.0.4 on 2019-04-15 00:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20190414_2343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockpicking',
            options={'ordering': ['-create_time', '-name']},
        ),
        migrations.AddField(
            model_name='stockpicking',
            name='create_date',
            field=models.DateField(default=datetime.datetime.today, verbose_name='创建日期'),
        ),
        migrations.AddField(
            model_name='stockpicking',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='stockpicking',
            name='done_date',
            field=models.DateField(blank=True, null=True, verbose_name='完成日期'),
        ),
        migrations.AddField(
            model_name='stockpicking',
            name='expect_date',
            field=models.DateField(blank=True, null=True, verbose_name='预计完成日期'),
        ),
        migrations.AddField(
            model_name='stockpicking',
            name='from_contact',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='源位置联系方式'),
        ),
        migrations.AddField(
            model_name='stockpicking',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stockpicking',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='stockpicking',
            name='picking_diff_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='作业类型特殊编码'),
        ),
        migrations.AddField(
            model_name='stockpicking',
            name='picking_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.StockPickingType', verbose_name='作业类型'),
        ),
        migrations.AddField(
            model_name='stockpicking',
            name='purchase_order_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='采购单ID'),
        ),
        migrations.AddField(
            model_name='stockpicking',
            name='real_price_total',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='实际含税金额'),
        ),
        migrations.AddField(
            model_name='stockpicking',
            name='return_note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='退货原因'),
        ),
        migrations.AddField(
            model_name='stockpicking',
            name='sale_order_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='销售单ID'),
        ),
        migrations.AddField(
            model_name='stockpicking',
            name='state',
            field=models.CharField(choices=[('draft', '草稿'), ('wait', '等待'), ('ready', '就绪'), ('pending', '待审核'), ('done', '完成'), ('cancel', '取消')], default='draft', max_length=255, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='stockpicking',
            name='to_contact',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='目的位置联系方式'),
        ),
    ]
