# Generated by Django 2.0.4 on 2019-04-21 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20190419_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockpickingtype',
            name='op_type',
            field=models.CharField(choices=[('INBOUND', '入库类型'), ('OUTBOUND', '出库类型'), ('INTERNAL', '内部')], default='INTERNAL', max_length=255, verbose_name='出入站类型'),
        ),
    ]
