# Generated by Django 2.0.4 on 2019-04-21 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_auto_20190421_0113'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockMove',
        ),
        migrations.DeleteModel(
            name='StockMoveLine',
        ),
        migrations.DeleteModel(
            name='StockProductionLot',
        ),
        migrations.DeleteModel(
            name='StockQuantity',
        ),
        migrations.AlterField(
            model_name='stocklocation',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_location_list', to='stock.StockLocation', verbose_name='上级位置'),
        ),
        migrations.AlterField(
            model_name='stockpicking',
            name='destination_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picking_destination_list', to='stock.StockLocation', verbose_name='目的位置'),
        ),
        migrations.AlterField(
            model_name='stockpicking',
            name='source_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picking_source_list', to='stock.StockLocation', verbose_name='来源位置'),
        ),
        migrations.AlterField(
            model_name='stockpickingtype',
            name='default_destination_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picking_type_destination_list', to='stock.StockLocation', verbose_name='默认目的位置'),
        ),
        migrations.AlterField(
            model_name='stockpickingtype',
            name='default_source_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picking_type_source_list', to='stock.StockLocation', verbose_name='默认来源位置'),
        ),
    ]
