# Generated by Django 2.0.4 on 2019-04-21 23:13

import base.utils
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LooksGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='外观组')),
                ('code', models.CharField(default='', max_length=255, verbose_name='编号')),
                ('desc', models.CharField(default='', max_length=255, verbose_name='描述')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-name'],
                'db_table': 'product_looks_group',
            },
        ),
        migrations.CreateModel(
            name='LooksInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='外观')),
                ('code', models.CharField(default='', max_length=255, verbose_name='编号')),
                ('desc', models.CharField(default='', max_length=255, verbose_name='描述')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.LooksGroup', verbose_name='外观组')),
            ],
            options={
                'ordering': ['-name'],
                'db_table': 'product_looks_info',
            },
        ),
        migrations.CreateModel(
            name='PartsGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='配件组')),
                ('code', models.CharField(default='', max_length=255, verbose_name='编号')),
                ('desc', models.CharField(default='', max_length=255, verbose_name='描述')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-name'],
                'db_table': 'product_parts_group',
            },
        ),
        migrations.CreateModel(
            name='PartsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='配件')),
                ('code', models.CharField(default='', max_length=255, verbose_name='编号')),
                ('desc', models.CharField(default='', max_length=255, verbose_name='描述')),
                ('max_available_qty', models.CharField(default='1', max_length=255, verbose_name='最大可用数量')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True)),
                ('default_looks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.LooksInfo', verbose_name='默认外观')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.PartsGroup', verbose_name='配件组')),
                ('parts_uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.BaseUnit', verbose_name='配件默认数量单位')),
            ],
            options={
                'ordering': ['-name'],
                'db_table': 'product_parts_info',
            },
        ),
        migrations.CreateModel(
            name='PartsLooksMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='选配名称')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True)),
                ('exclude_looks_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='map_exclude_looks_list', to='product.LooksInfo', verbose_name='例外色板')),
                ('looks_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.LooksGroup', verbose_name='色板组')),
                ('looks_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='map_looks_list', to='product.LooksInfo', verbose_name='色板')),
                ('parts_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.PartsInfo', verbose_name='配件范围')),
            ],
            options={
                'ordering': ['create_time'],
                'db_table': 'product_parts_looks_map',
            },
        ),
        migrations.CreateModel(
            name='PartsLooksPriceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_price', models.CharField(default='0', max_length=255, verbose_name='产品标价(指导售价)')),
                ('sale_price', models.CharField(default='0', max_length=255, verbose_name='销售价格')),
                ('purchase_price', models.CharField(default='0', max_length=255, verbose_name='采购价格')),
                ('standard_price', models.CharField(default='0', max_length=255, verbose_name='成本价格')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True)),
                ('looks_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.LooksGroup', verbose_name='色板组')),
                ('looks_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.LooksInfo', verbose_name='色板')),
            ],
            options={
                'ordering': ['create_time'],
                'db_table': 'prats_looks_price_item',
            },
        ),
        migrations.CreateModel(
            name='PartsLooksPriceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='选配定价单')),
                ('code', models.CharField(default='', max_length=255, verbose_name='编号')),
                ('date_start', models.DateField(default=datetime.datetime.today, verbose_name='开始日期')),
                ('date_end', models.DateField(default=datetime.datetime.today, verbose_name='结束日期')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Company', verbose_name='所属公司')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Currency', verbose_name='货币')),
                ('parts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.PartsInfo', verbose_name='所属配件')),
                ('unit_uom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.BaseUnit', verbose_name='单价数量单位')),
            ],
            options={
                'ordering': ['create_time'],
                'db_table': 'prats_looks_price_list',
            },
        ),
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='产品品牌')),
                ('code', models.CharField(default='', max_length=255, verbose_name='编号')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-name'],
                'db_table': 'product_brand',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='产品类别')),
                ('code', models.CharField(default='', max_length=255, verbose_name='编号')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-name'],
                'db_table': 'product_category',
            },
        ),
        migrations.CreateModel(
            name='ProductPacking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='包装名称')),
                ('code', models.CharField(default='', max_length=255, verbose_name='编号')),
                ('desc', models.CharField(max_length=255, verbose_name='选配描述')),
                ('pack_qty', models.CharField(default='1', max_length=255, verbose_name='套装数量')),
                ('product_qty', models.CharField(default='1', max_length=255, verbose_name='当前单位数量')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True)),
                ('pack_uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packing_pack_uom_list', to='base.BaseUnit', verbose_name='包装默认单位')),
            ],
            options={
                'ordering': ['create_time'],
                'db_table': 'product_packing',
            },
        ),
        migrations.CreateModel(
            name='ProductPackingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parts_qty', models.CharField(default='1', max_length=255, verbose_name='配件数量')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True)),
                ('looks_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.LooksInfo', verbose_name='配件色板')),
                ('packing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_list', to='product.ProductPacking')),
                ('parts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.PartsInfo', verbose_name='配件')),
                ('parts_uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.BaseUnit', verbose_name='配件单位')),
            ],
            options={
                'ordering': ['create_time'],
                'db_table': 'product_packing_list',
            },
        ),
        migrations.CreateModel(
            name='ProductPriceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rounding', models.CharField(default='0.00', max_length=255, verbose_name='精度')),
                ('mark_price', models.CharField(default='0', max_length=255, verbose_name='产品标价(指导售价)')),
                ('sale_price', models.CharField(default='0', max_length=255, verbose_name='销售价格')),
                ('purchase_price', models.CharField(default='0', max_length=255, verbose_name='采购价格')),
                ('standard_price', models.CharField(default='0', max_length=255, verbose_name='成本价格')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['create_time'],
                'db_table': 'product_price_item',
            },
        ),
        migrations.CreateModel(
            name='ProductPriceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='产品价格单')),
                ('code', models.CharField(default='', max_length=255, verbose_name='编号')),
                ('date_start', models.DateField(default=datetime.datetime.today, verbose_name='开始日期')),
                ('date_end', models.DateField(default=datetime.datetime.today, verbose_name='结束日期')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Company', verbose_name='所属公司')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Currency', verbose_name='货币')),
            ],
            options={
                'ordering': ['create_time'],
                'db_table': 'product_price_list',
            },
        ),
        migrations.CreateModel(
            name='ProductProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='产品名称')),
                ('code', models.CharField(default='', max_length=255, verbose_name='编号')),
                ('desc', models.CharField(default='', max_length=255, verbose_name='产品描述')),
                ('product_image', models.ImageField(default='default_logo.png', storage=base.utils.CustomFileStorage(), upload_to='product_image/', verbose_name='产品图片')),
                ('product_display_rank', models.CharField(default='', max_length=255, verbose_name='产品显示排序')),
                ('is_dummy_special_product', models.BooleanField(default=False, verbose_name='特殊定制？(虚拟)')),
                ('product_type', models.CharField(choices=[('STD', '标准产品'), ('PART', '零件'), ('SERVE', '服务类'), ('VIRTUAL', '虚拟类'), ('PACKAGE', '包装类(不能单个存在)')], default='STD', max_length=255, verbose_name='产品属性')),
                ('product_usage_type', models.CharField(choices=[('NORMAL', '正常'), ('STOP_SALE', '停售'), ('STOP_PRODUCTION', '停产'), ('PRE_SALE', '预售'), ('SOLD_OUT', '下架'), ('DISABLE', '禁用')], default='NORMAL', max_length=255, verbose_name='产品销售属性')),
                ('product_length', models.CharField(default='', max_length=255, verbose_name='产品(长)')),
                ('product_width', models.CharField(default='', max_length=255, verbose_name='产品(宽)')),
                ('product_height', models.CharField(default='', max_length=255, verbose_name='产品(高)')),
                ('can_sale', models.BooleanField(default=True, verbose_name='可以销售？')),
                ('can_purchase', models.BooleanField(default=True, verbose_name='可以采购？')),
                ('use_stock', models.BooleanField(default=True, verbose_name='使用库存？')),
                ('stock_tracking', models.CharField(choices=[('LOT', '批次追踪'), ('SERIAL', '序列追踪'), ('NONE', '无')], default='LOT', max_length=255, verbose_name='产品库存追踪')),
                ('barcode', models.CharField(default='', max_length=255, verbose_name='商品条码')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.ProductBrand', verbose_name='所属品牌')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.ProductCategory', verbose_name='所属类别')),
                ('default_unit_uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_unit_uom_list', to='base.BaseUnit', verbose_name='默认数量单位')),
                ('default_volume_uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_volume_uom_list', to='base.BaseUnit', verbose_name='默认体积单位')),
            ],
            options={
                'ordering': ['-name'],
                'db_table': 'product_product',
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='产品标签')),
                ('code', models.CharField(default='', max_length=255, verbose_name='编号')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_product_tags', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'ordering': ['-name'],
                'db_table': 'product_tag',
            },
        ),
        migrations.AddField(
            model_name='productproduct',
            name='tags',
            field=models.ManyToManyField(blank=True, to='product.ProductTag', verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='productpriceitem',
            name='price_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductPriceList', verbose_name='产品价格单'),
        ),
        migrations.AddField(
            model_name='productpriceitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_price_list', to='product.ProductProduct', verbose_name='产品'),
        ),
        migrations.AddField(
            model_name='productpriceitem',
            name='unit_uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.BaseUnit', verbose_name='单价数量单位'),
        ),
        migrations.AddField(
            model_name='productpacking',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductProduct', verbose_name='主产品'),
        ),
        migrations.AddField(
            model_name='productpacking',
            name='product_uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packing_product_uom_list', to='base.BaseUnit', verbose_name='产品单位'),
        ),
        migrations.AddField(
            model_name='partslookspriceitem',
            name='price_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.PartsLooksPriceList', verbose_name='价格单'),
        ),
        migrations.AddField(
            model_name='partsinfo',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_parts_list', to='product.ProductProduct', verbose_name='所属产品'),
        ),
    ]
