# Generated by Django 2.0.4 on 2019-04-17 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='产品品牌')),
                ('code', models.CharField(max_length=255, verbose_name='编号')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-name'],
                'db_table': 'product_brand',
            },
        ),
        migrations.CreateModel(
            name='ProductSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='产品系列')),
                ('code', models.CharField(max_length=255, verbose_name='编号')),
                ('is_common_series', models.BooleanField(default=False, verbose_name='通用系列? ')),
                ('is_active', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductBrand', verbose_name='所属品牌')),
            ],
            options={
                'ordering': ['-name'],
                'db_table': 'product_series',
            },
        ),
        migrations.CreateModel(
            name='ProductStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='产品款式')),
                ('code', models.CharField(max_length=255, verbose_name='编号')),
                ('is_active', models.BooleanField(default=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductSeries', verbose_name='所属系列')),
            ],
            options={
                'ordering': ['-name'],
                'db_table': 'product_style',
            },
        ),
    ]
