# Generated by Django 2.0.4 on 2019-04-25 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpricelist',
            name='name',
            field=models.CharField(default='ProductPriceList8200', max_length=255, verbose_name='产品价格单'),
        ),
    ]
