# Generated by Django 2.0.4 on 2019-04-21 01:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='产品类别')),
                ('code', models.CharField(default='', max_length=255, verbose_name='编号')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'product_category',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='ProductProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='产品标签')),
                ('code', models.CharField(default='', max_length=255, verbose_name='编号')),
            ],
            options={
                'db_table': 'product_product',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='产品标签')),
                ('code', models.CharField(default='', max_length=255, verbose_name='编号')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_tags', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'db_table': 'product_tag',
                'ordering': ['-name'],
            },
        ),
        migrations.RemoveField(
            model_name='productseries',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='productstyle',
            name='series',
        ),
        migrations.AddField(
            model_name='productbrand',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='productbrand',
            name='code',
            field=models.CharField(default='', max_length=255, verbose_name='编号'),
        ),
        migrations.DeleteModel(
            name='ProductSeries',
        ),
        migrations.DeleteModel(
            name='ProductStyle',
        ),
        migrations.AddField(
            model_name='productproduct',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.ProductBrand', verbose_name='所属品牌'),
        ),
        migrations.AddField(
            model_name='productproduct',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.ProductCategory', verbose_name='所属类别'),
        ),
        migrations.AddField(
            model_name='productproduct',
            name='tags',
            field=models.ManyToManyField(blank=True, to='product.ProductTag', verbose_name='标签'),
        ),
    ]
