# Generated by Django 2.0.4 on 2019-04-16 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20190416_2323'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='产品款式')),
                ('code', models.CharField(max_length=255, verbose_name='编号')),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Company')),
            ],
            options={
                'db_table': 'product_style',
                'ordering': ['-name'],
            },
        ),
        migrations.AddField(
            model_name='productseries',
            name='is_common_series',
            field=models.BooleanField(default=False, verbose_name='通用系列? '),
        ),
        migrations.AlterField(
            model_name='productbrand',
            name='name',
            field=models.CharField(max_length=255, verbose_name='产品品牌'),
        ),
        migrations.AlterField(
            model_name='productseries',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductBrand', verbose_name='所属品牌'),
        ),
        migrations.AlterField(
            model_name='productseries',
            name='name',
            field=models.CharField(max_length=255, verbose_name='产品系列'),
        ),
        migrations.AddField(
            model_name='productstyle',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductSeries', verbose_name='所属系列'),
        ),
    ]
