# Generated by Django 2.0.4 on 2019-04-21 12:47

import base.utils
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20190418_1652'),
        ('product', '0002_auto_20190421_0145'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPriceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rounding', models.CharField(default='0.00', max_length=255, verbose_name='精度')),
                ('mark_price', models.CharField(default='0', max_length=255, verbose_name='产品标价(指导售价)')),
                ('sale_price', models.CharField(default='0', max_length=255, verbose_name='销售价格')),
                ('purchase_price', models.CharField(default='0', max_length=255, verbose_name='采购价格')),
                ('standard_price', models.CharField(default='0', max_length=255, verbose_name='成本价格')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'product_price_item',
                'ordering': ['create_time'],
            },
        ),
        migrations.CreateModel(
            name='ProductPriceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='产品价格单')),
                ('code', models.CharField(default='', max_length=255, verbose_name='编号')),
                ('date_start', models.DateField(default=datetime.datetime.today, verbose_name='开始日期')),
                ('date_end', models.DateField(default=datetime.datetime.today, verbose_name='结束日期')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_product_price_lists', to='base.Company', verbose_name='所属公司')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Currency', verbose_name='货币')),
            ],
            options={
                'db_table': 'product_price_list',
                'ordering': ['create_time'],
            },
        ),
        migrations.AddField(
            model_name='productproduct',
            name='barcode',
            field=models.CharField(default='', max_length=255, verbose_name='商品条码'),
        ),
        migrations.AddField(
            model_name='productproduct',
            name='can_purchase',
            field=models.BooleanField(default=True, verbose_name='可以采购？'),
        ),
        migrations.AddField(
            model_name='productproduct',
            name='can_sale',
            field=models.BooleanField(default=True, verbose_name='可以销售？'),
        ),
        migrations.AddField(
            model_name='productproduct',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='productproduct',
            name='default_unit_uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.BaseUnit', verbose_name='默认数量单位'),
        ),
        migrations.AddField(
            model_name='productproduct',
            name='desc',
            field=models.CharField(default='', max_length=255, verbose_name='产品描述'),
        ),
        migrations.AddField(
            model_name='productproduct',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productproduct',
            name='is_dummy_special_product',
            field=models.BooleanField(default=False, verbose_name='特殊定制？(虚拟)'),
        ),
        migrations.AddField(
            model_name='productproduct',
            name='product_display_rank',
            field=models.CharField(default='', max_length=255, verbose_name='产品显示排序'),
        ),
        migrations.AddField(
            model_name='productproduct',
            name='product_image',
            field=models.ImageField(default='default_logo.png', storage=base.utils.CustomFileStorage(), upload_to='product_image/', verbose_name='产品图片'),
        ),
        migrations.AddField(
            model_name='productproduct',
            name='product_type',
            field=models.CharField(choices=[('STD', '标准产品'), ('PART', '零件'), ('SERVE', '服务类'), ('VIRTUAL', '虚拟类'), ('PACKAGE', '包装类(不能单个存在)')], default='STD', max_length=255, verbose_name='产品属性'),
        ),
        migrations.AddField(
            model_name='productproduct',
            name='product_usage_type',
            field=models.CharField(choices=[('NORMAL', '正常'), ('STOP_SALE', '停售'), ('STOP_PRODUCTION', '停产'), ('PRE_SALE', '预售'), ('SOLD_OUT', '下架'), ('DISABLE', '禁用')], default='NORMAL', max_length=255, verbose_name='产品可使用属性'),
        ),
        migrations.AddField(
            model_name='productproduct',
            name='product_volume',
            field=models.CharField(default='', max_length=255, verbose_name='产品体积描述'),
        ),
        migrations.AddField(
            model_name='productproduct',
            name='product_weight',
            field=models.CharField(default='', max_length=255, verbose_name='产品重量描述'),
        ),
        migrations.AddField(
            model_name='productproduct',
            name='stock_tracking',
            field=models.CharField(choices=[('LOT', '批次追踪'), ('SERIAL', '序列追踪'), ('NONE', '无')], default='LOT', max_length=255, verbose_name='产品库存追踪'),
        ),
        migrations.AddField(
            model_name='productproduct',
            name='use_stock',
            field=models.BooleanField(default=True, verbose_name='使用库存？'),
        ),
        migrations.AlterField(
            model_name='productproduct',
            name='name',
            field=models.CharField(max_length=255, verbose_name='产品名称'),
        ),
        migrations.AddField(
            model_name='productpriceitem',
            name='price_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_lists', to='product.ProductPriceList', verbose_name='产品价格单'),
        ),
        migrations.AddField(
            model_name='productpriceitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_price_items', to='product.ProductProduct', verbose_name='产品'),
        ),
        migrations.AddField(
            model_name='productpriceitem',
            name='unit_uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.BaseUnit', verbose_name='单价数量单位'),
        ),
    ]
