# Generated by Django 2.0.4 on 2019-04-25 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20190425_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpricelist',
            name='name',
            field=models.CharField(default='ProductPriceList6273', max_length=255, verbose_name='产品价格单'),
        ),
    ]
