# Generated by Django 2.0.4 on 2019-04-21 14:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20190421_1442'),
        ('product', '0003_auto_20190421_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppearanceGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='外观组')),
                ('code', models.CharField(default='', max_length=255, verbose_name='编号')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'product_appearance_group',
            },
        ),
        migrations.CreateModel(
            name='AppearanceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='外观')),
                ('code', models.CharField(default='', max_length=255, verbose_name='编号')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True)),
                ('appearance_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_items', to='product.AppearanceGroup', verbose_name='所属外观组')),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'product_appearance_item',
            },
        ),
        migrations.CreateModel(
            name='AppearanceItemPriceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rounding', models.CharField(default='0.00', max_length=255, verbose_name='精度')),
                ('mark_price', models.CharField(default='0', max_length=255, verbose_name='产品标价(指导售价)')),
                ('sale_price', models.CharField(default='0', max_length=255, verbose_name='销售价格')),
                ('purchase_price', models.CharField(default='0', max_length=255, verbose_name='采购价格')),
                ('standard_price', models.CharField(default='0', max_length=255, verbose_name='成本价格')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True)),
                ('looks_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_looks_price_items', to='product.AppearanceItem')),
            ],
            options={
                'ordering': ['create_time'],
                'db_table': 'product_looks_price_item',
            },
        ),
        migrations.CreateModel(
            name='AppearanceItemPriceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='外观价格单')),
                ('code', models.CharField(default='', max_length=255, verbose_name='编号')),
                ('date_start', models.DateField(default=datetime.datetime.today, verbose_name='开始日期')),
                ('date_end', models.DateField(default=datetime.datetime.today, verbose_name='结束日期')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_looks_price_lists', to='base.Company', verbose_name='所属公司')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Currency', verbose_name='货币')),
            ],
            options={
                'ordering': ['create_time'],
                'db_table': 'product_looks_price_list',
            },
        ),
        migrations.CreateModel(
            name='AppearanceMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True)),
                ('exclude_looks_items', models.ManyToManyField(blank=True, related_name='exclude_looks_items_map', to='product.AppearanceItem', verbose_name='排除外观')),
                ('looks_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.AppearanceGroup')),
                ('looks_items', models.ManyToManyField(blank=True, related_name='looks_items_map', to='product.AppearanceItem', verbose_name='选配外观')),
            ],
            options={
                'ordering': ['create_time'],
                'db_table': 'product_appearance_map',
            },
        ),
        migrations.CreateModel(
            name='AppearanceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='外观类型')),
                ('code', models.CharField(default='', max_length=255, verbose_name='编号')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductCategory', verbose_name='适用产品类别')),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'product_appearance_type',
            },
        ),
        migrations.CreateModel(
            name='ProductParts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='配件名称')),
                ('code', models.CharField(default='', max_length=255, verbose_name='编号')),
                ('desc', models.CharField(default='', max_length=255, verbose_name='描述')),
                ('parts_volume', models.CharField(default='', max_length=255, verbose_name='配件体积描述')),
                ('parts_weight', models.CharField(default='', max_length=255, verbose_name='配件重量描述')),
                ('max_available_qty', models.CharField(default='1', max_length=255, verbose_name='最大可用数量(1 -- max)')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'product_parts',
            },
        ),
        migrations.CreateModel(
            name='ProductPartsPriceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rounding', models.CharField(default='0.00', max_length=255, verbose_name='精度')),
                ('mark_price', models.CharField(default='0', max_length=255, verbose_name='产品标价(指导售价)')),
                ('sale_price', models.CharField(default='0', max_length=255, verbose_name='销售价格')),
                ('purchase_price', models.CharField(default='0', max_length=255, verbose_name='采购价格')),
                ('standard_price', models.CharField(default='0', max_length=255, verbose_name='成本价格')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True)),
                ('parts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_items', to='product.ProductParts')),
            ],
            options={
                'ordering': ['create_time'],
                'db_table': 'product_parts_price_item',
            },
        ),
        migrations.CreateModel(
            name='ProductPartsPriceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='配件价格单')),
                ('code', models.CharField(default='', max_length=255, verbose_name='编号')),
                ('date_start', models.DateField(default=datetime.datetime.today, verbose_name='开始日期')),
                ('date_end', models.DateField(default=datetime.datetime.today, verbose_name='结束日期')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_parts_price_lists', to='base.Company', verbose_name='所属公司')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Currency', verbose_name='货币')),
            ],
            options={
                'ordering': ['create_time'],
                'db_table': 'product_parts_price_list',
            },
        ),
        migrations.AddField(
            model_name='productpartspriceitem',
            name='price_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_price', to='product.ProductPartsPriceList'),
        ),
        migrations.AddField(
            model_name='productpartspriceitem',
            name='unit_uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.BaseUnit', verbose_name='单价数量单位'),
        ),
        migrations.AddField(
            model_name='appearancemap',
            name='looks_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.AppearanceType'),
        ),
        migrations.AddField(
            model_name='appearancemap',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_appearance', to='product.ProductProduct', verbose_name='产品'),
        ),
        migrations.AddField(
            model_name='appearanceitempriceitem',
            name='price_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='looks_items_price', to='product.AppearanceItemPriceList'),
        ),
        migrations.AddField(
            model_name='appearanceitempriceitem',
            name='unit_uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.BaseUnit', verbose_name='单价数量单位'),
        ),
        migrations.AddField(
            model_name='appearancegroup',
            name='appearance_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.AppearanceType', verbose_name='外观组'),
        ),
        migrations.AddField(
            model_name='productproduct',
            name='product_parts',
            field=models.ManyToManyField(blank=True, to='product.ProductParts', verbose_name='产品配件列表'),
        ),
    ]
