# Generated by Django 2.0.4 on 2019-04-25 22:42

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20190425_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpricelist',
            name='name',
            field=models.CharField(default=product.models._get_default_name, max_length=255, verbose_name='产品价格单'),
        ),
    ]
