# Generated by Django 2.0.4 on 2019-04-21 15:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20190421_1442'),
        ('product', '0004_auto_20190421_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='包装名称')),
                ('code', models.CharField(default='', max_length=255, verbose_name='编号')),
                ('desc', models.CharField(default='', max_length=255, verbose_name='描述')),
                ('product_type', models.CharField(choices=[('STD', '标准产品'), ('PART', '零件'), ('SERVE', '服务类'), ('VIRTUAL', '虚拟类'), ('PACKAGE', '包装类(不能单个存在)')], default='STD', max_length=255, verbose_name='产品属性')),
                ('product_usage_type', models.CharField(choices=[('NORMAL', '正常'), ('STOP_SALE', '停售'), ('STOP_PRODUCTION', '停产'), ('PRE_SALE', '预售'), ('SOLD_OUT', '下架'), ('DISABLE', '禁用')], default='NORMAL', max_length=255, verbose_name='产品可使用属性')),
                ('product_volume', models.CharField(default='', max_length=255, verbose_name='产品体积描述')),
                ('product_weight', models.CharField(default='', max_length=255, verbose_name='产品重量描述')),
                ('can_sale', models.BooleanField(default=True, verbose_name='可以销售？')),
                ('can_purchase', models.BooleanField(default=True, verbose_name='可以采购？')),
                ('use_stock', models.BooleanField(default=True, verbose_name='使用库存？')),
                ('stock_tracking', models.CharField(choices=[('LOT', '批次追踪'), ('SERIAL', '序列追踪'), ('NONE', '无')], default='LOT', max_length=255, verbose_name='产品库存追踪')),
                ('barcode', models.CharField(default='', max_length=255, verbose_name='商品条码')),
                ('set_number', models.CharField(default='1', max_length=255, verbose_name='包含套数')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.ProductBrand', verbose_name='所属品牌')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.ProductCategory', verbose_name='所属类别')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_packages', to='base.Company', verbose_name='创建公司')),
                ('looks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.AppearanceItem', verbose_name='主产品外观')),
                ('package_uom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_uoms', to='base.BaseUnit', verbose_name='包装单位')),
            ],
            options={
                'db_table': 'product_package',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductPackagePartsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parts_qty', models.CharField(default='1', max_length=255, verbose_name='配件数量')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_parts_list', to='product.ProductPackage')),
                ('parts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductParts', verbose_name='配件')),
                ('parts_uom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.BaseUnit', verbose_name='配件单位')),
            ],
            options={
                'db_table': 'product_package_parts_list',
                'ordering': ['package'],
            },
        ),
        migrations.CreateModel(
            name='ProductPartsMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True)),
                ('parts_list', models.ManyToManyField(blank=True, to='product.ProductParts')),
            ],
            options={
                'db_table': 'product_parts_map',
                'ordering': ['create_time'],
            },
        ),
        migrations.RemoveField(
            model_name='productproduct',
            name='product_parts',
        ),
        migrations.AddField(
            model_name='appearanceitempriceitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.ProductProduct', verbose_name='对应产品'),
        ),
        migrations.AlterField(
            model_name='productpartspriceitem',
            name='parts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_items', to='product.ProductParts', verbose_name='配件'),
        ),
        migrations.AlterField(
            model_name='productpartspriceitem',
            name='price_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_price', to='product.ProductPartsPriceList', verbose_name='配件价格单'),
        ),
        migrations.AddField(
            model_name='productpartsmap',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_parts_map', to='product.ProductProduct'),
        ),
        migrations.AddField(
            model_name='productpackage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductProduct', verbose_name='主产品'),
        ),
        migrations.AddField(
            model_name='productpackage',
            name='product_uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_product_uoms', to='base.BaseUnit', verbose_name='主产品单位'),
        ),
    ]
