# Generated by Django 2.0.4 on 2019-04-21 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20190421_1824'),
        ('product', '0005_auto_20190421_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appearancegroup',
            name='appearance_type',
        ),
        migrations.RemoveField(
            model_name='appearanceitem',
            name='appearance_group',
        ),
        migrations.RemoveField(
            model_name='appearanceitempriceitem',
            name='looks_item',
        ),
        migrations.RemoveField(
            model_name='appearanceitempriceitem',
            name='price_list',
        ),
        migrations.RemoveField(
            model_name='appearanceitempriceitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='appearanceitempriceitem',
            name='unit_uom',
        ),
        migrations.RemoveField(
            model_name='appearanceitempricelist',
            name='company',
        ),
        migrations.RemoveField(
            model_name='appearanceitempricelist',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='appearancemap',
            name='exclude_looks_items',
        ),
        migrations.RemoveField(
            model_name='appearancemap',
            name='looks_group',
        ),
        migrations.RemoveField(
            model_name='appearancemap',
            name='looks_items',
        ),
        migrations.RemoveField(
            model_name='appearancemap',
            name='looks_type',
        ),
        migrations.RemoveField(
            model_name='appearancemap',
            name='product',
        ),
        migrations.RemoveField(
            model_name='appearancetype',
            name='product_category',
        ),
        migrations.RemoveField(
            model_name='productpackage',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='productpackage',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productpackage',
            name='company',
        ),
        migrations.RemoveField(
            model_name='productpackage',
            name='looks',
        ),
        migrations.RemoveField(
            model_name='productpackage',
            name='package_uom',
        ),
        migrations.RemoveField(
            model_name='productpackage',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productpackage',
            name='product_uom',
        ),
        migrations.RemoveField(
            model_name='productpackagepartslist',
            name='package',
        ),
        migrations.RemoveField(
            model_name='productpackagepartslist',
            name='parts',
        ),
        migrations.RemoveField(
            model_name='productpackagepartslist',
            name='parts_uom',
        ),
        migrations.RemoveField(
            model_name='productpartsmap',
            name='parts_list',
        ),
        migrations.RemoveField(
            model_name='productpartsmap',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productpartspriceitem',
            name='parts',
        ),
        migrations.RemoveField(
            model_name='productpartspriceitem',
            name='price_list',
        ),
        migrations.RemoveField(
            model_name='productpartspriceitem',
            name='unit_uom',
        ),
        migrations.RemoveField(
            model_name='productpartspricelist',
            name='company',
        ),
        migrations.RemoveField(
            model_name='productpartspricelist',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='productproduct',
            name='product_volume',
        ),
        migrations.RemoveField(
            model_name='productproduct',
            name='product_weight',
        ),
        migrations.AddField(
            model_name='productproduct',
            name='default_volume_uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_volume_uom_list', to='base.BaseUnit', verbose_name='默认体积单位'),
        ),
        migrations.AddField(
            model_name='productproduct',
            name='product_height',
            field=models.CharField(default='', max_length=255, verbose_name='产品(高)'),
        ),
        migrations.AddField(
            model_name='productproduct',
            name='product_length',
            field=models.CharField(default='', max_length=255, verbose_name='产品(长)'),
        ),
        migrations.AddField(
            model_name='productproduct',
            name='product_width',
            field=models.CharField(default='', max_length=255, verbose_name='产品(宽)'),
        ),
        migrations.AlterField(
            model_name='productpriceitem',
            name='price_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductPriceList', verbose_name='产品价格单'),
        ),
        migrations.AlterField(
            model_name='productpriceitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_price_list', to='product.ProductProduct', verbose_name='产品'),
        ),
        migrations.AlterField(
            model_name='productpricelist',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Company', verbose_name='所属公司'),
        ),
        migrations.AlterField(
            model_name='productproduct',
            name='default_unit_uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_unit_uom_list', to='base.BaseUnit', verbose_name='默认数量单位'),
        ),
        migrations.AlterField(
            model_name='productproduct',
            name='product_usage_type',
            field=models.CharField(choices=[('NORMAL', '正常'), ('STOP_SALE', '停售'), ('STOP_PRODUCTION', '停产'), ('PRE_SALE', '预售'), ('SOLD_OUT', '下架'), ('DISABLE', '禁用')], default='NORMAL', max_length=255, verbose_name='产品销售属性'),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_product_tags', to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
        migrations.DeleteModel(
            name='AppearanceGroup',
        ),
        migrations.DeleteModel(
            name='AppearanceItem',
        ),
        migrations.DeleteModel(
            name='AppearanceItemPriceItem',
        ),
        migrations.DeleteModel(
            name='AppearanceItemPriceList',
        ),
        migrations.DeleteModel(
            name='AppearanceMap',
        ),
        migrations.DeleteModel(
            name='AppearanceType',
        ),
        migrations.DeleteModel(
            name='ProductPackage',
        ),
        migrations.DeleteModel(
            name='ProductPackagePartsList',
        ),
        migrations.DeleteModel(
            name='ProductParts',
        ),
        migrations.DeleteModel(
            name='ProductPartsMap',
        ),
        migrations.DeleteModel(
            name='ProductPartsPriceItem',
        ),
        migrations.DeleteModel(
            name='ProductPartsPriceList',
        ),
    ]
