# Generated by Django 2.0.4 on 2019-04-28 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20190428_1736'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classcoursemap',
            unique_together={('grade_info', 'base_class', 'course')},
        ),
    ]
