# Generated by Django 2.0.4 on 2019-04-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20190428_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='teachers',
            field=models.ManyToManyField(blank=True, to='school.Teacher', verbose_name='教该课程的老师'),
        ),
    ]
