# Generated by Django 2.0.4 on 2019-04-28 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_material_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='read_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teacher_read_examination', to='school.Teacher', verbose_name='阅卷老师'),
        ),
        migrations.AlterField(
            model_name='examination',
            name='course_map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.ClassCourseMap', verbose_name='课程'),
        ),
        migrations.AlterField(
            model_name='examination',
            name='invigilator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invigilator_examination', to='school.Teacher', verbose_name='监考老师'),
        ),
        migrations.AlterField(
            model_name='scorerecord',
            name='score_level',
            field=models.CharField(default='', max_length=255, verbose_name='得分等级'),
        ),
    ]
