# Generated by Django 2.0.4 on 2019-04-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_examination_is_create_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='full_score_tag',
            field=models.CharField(default='100', max_length=255, verbose_name='满分'),
        ),
    ]
