# Generated by Django 2.0.4 on 2019-04-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_material_full_score_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorerecord',
            name='real_score',
            field=models.CharField(default='', max_length=255, verbose_name='实际分数'),
        ),
        migrations.AlterField(
            model_name='scorerecord',
            name='score',
            field=models.CharField(default='', max_length=255, verbose_name='分数(100值)'),
        ),
    ]
