# Generated by Django 2.0.4 on 2019-04-29 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_auto_20190428_1955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scorerecord',
            options={'ordering': ['examination', '-score']},
        ),
    ]
