# Generated by Django 2.0.4 on 2019-04-22 23:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='Username')),
                ('email', models.CharField(default='', max_length=255, verbose_name='Email')),
                ('is_admin', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-create_time'],
                'db_table': 'base_user',
            },
        ),
        migrations.CreateModel(
            name='BaseCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='城市')),
                ('area_code', models.CharField(max_length=255, verbose_name='城市区号')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'base_city',
            },
        ),
        migrations.CreateModel(
            name='BaseUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='单位')),
                ('unit_symbol', models.CharField(max_length=255, verbose_name='单位符号')),
                ('unit_type', models.CharField(choices=[('UNIT', '数量单位'), ('TIME', '时间'), ('LENGTH', '长度'), ('WEIGHT', '重量')], default='UNIT', max_length=255, verbose_name='单位类型')),
                ('is_base_unit', models.BooleanField(default=False, verbose_name='是否为基本单位')),
                ('rounding', models.CharField(default='0.00', max_length=255, verbose_name='精度')),
                ('factor', models.CharField(default='1', max_length=255, verbose_name='倍数')),
                ('compute_method', models.CharField(choices=[('std', '相等'), ('multi', '乘'), ('divide', '除')], default='std', max_length=255, verbose_name='计算方式')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['unit_type', 'name'],
                'db_table': 'base_unit',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='省')),
                ('short_name', models.CharField(max_length=255, verbose_name='简称')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'base_province',
            },
        ),
        migrations.AddField(
            model_name='basecity',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='base.Province', verbose_name='所在省份'),
        ),
    ]
