# Generated by Django 2.0.4 on 2019-04-14 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='induction_date',
            field=models.DateField(blank=True, null=True, verbose_name='入职日期'),
        ),
        migrations.AddField(
            model_name='partner',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间'),
        ),
    ]
