# Generated by Django 2.0.4 on 2019-04-24 23:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='职称')),
                ('code', models.CharField(default='', max_length=255, verbose_name='Code')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='部门名称')),
                ('code', models.CharField(default='', max_length=255, verbose_name='Code')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_departments', to='base.Company', verbose_name='所在公司')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='序列号名称')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='指定编码')),
                ('padding', models.IntegerField(default=5, verbose_name='填充长度')),
                ('step_len', models.IntegerField(default=1, verbose_name='步长')),
                ('next_number', models.IntegerField(default=1, verbose_name='下个序列号')),
                ('suffix', models.CharField(default='', max_length=255, verbose_name='后缀')),
                ('prefix', models.CharField(default='', max_length=255, verbose_name='前缀')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserOperationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=255, verbose_name='所在app名称')),
                ('model_name', models.CharField(max_length=255, verbose_name='操作的模型')),
                ('model_id', models.CharField(max_length=255, verbose_name='操作模型的id')),
                ('content', models.CharField(default='', max_length=255, verbose_name='操作内容')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-create_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='baseuser',
            options={'ordering': ['username', '-create_time']},
        ),
        migrations.AddField(
            model_name='basecity',
            name='is_municipality',
            field=models.BooleanField(default=False, verbose_name='直辖市'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='is_department_manager',
            field=models.BooleanField(default=False, verbose_name='部门经理'),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_users', to='base.Company', verbose_name='所属公司'),
        ),
        migrations.AddField(
            model_name='useroperationlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_op_logs', to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_users', to='base.Department', verbose_name='所属部门'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.BaseJob', verbose_name='职称'),
        ),
    ]
