# Generated by Django 2.0.4 on 2019-04-13 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20190413_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'base_user_group',
            },
        ),
        migrations.AddField(
            model_name='basecountry',
            name='short_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='简称'),
        ),
        migrations.AddField(
            model_name='department',
            name='department_type',
            field=models.CharField(choices=[('NORMAL', '常规'), ('SPECIAL', '特殊'), ('STORE', '子公司门店'), ('OTHER', '其他')], default='NORMAL', max_length=255, verbose_name='部门类型'),
        ),
        migrations.AddField(
            model_name='department',
            name='parent_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_departments', to='base.Department', verbose_name='上级部门'),
        ),
        migrations.AddField(
            model_name='partner',
            name='is_customer',
            field=models.BooleanField(default=True, verbose_name='是否是客户'),
        ),
        migrations.AddField(
            model_name='partner',
            name='is_supplier',
            field=models.BooleanField(default=True, verbose_name='是否是供应商'),
        ),
    ]
