# Generated by Django 2.0.4 on 2019-04-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20190414_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecity',
            name='is_provincial_capital',
            field=models.BooleanField(default=False, verbose_name='省会城市'),
        ),
    ]
