# Generated by Django 2.0.4 on 2019-04-17 13:47

import base.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20190417_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecountry',
            name='national_flag',
            field=models.ImageField(default='default_logo.png', storage=base.utils.CustomFileStorage(), upload_to='country_image/', verbose_name='国旗图标'),
        ),
    ]
