# Generated by Django 2.0.4 on 2019-04-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20190426_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileobject',
            name='file_type',
            field=models.CharField(default='', max_length=255, verbose_name='文件类型'),
        ),
        migrations.AddField(
            model_name='fileobject',
            name='model_field',
            field=models.CharField(default='', max_length=255, verbose_name='所属字段'),
        ),
        migrations.AlterField(
            model_name='fileobject',
            name='app_label',
            field=models.CharField(default='', max_length=255, verbose_name='所属APP'),
        ),
        migrations.AlterField(
            model_name='fileobject',
            name='model_id',
            field=models.CharField(default='', max_length=255, verbose_name='所属对象ID'),
        ),
        migrations.AlterField(
            model_name='fileobject',
            name='model_name',
            field=models.CharField(default='', max_length=255, verbose_name='所属模型'),
        ),
    ]
