# Generated by Django 2.0.4 on 2019-04-13 16:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20190413_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='唯一编码'),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='用户组名'),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_groups', to='base.UserGroup', verbose_name='上级用户组'),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
