# Generated by Django 2.0.4 on 2019-04-17 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20190417_1347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basecountry',
            options={'ordering': ['name']},
        ),
    ]
