# Generated by Django 2.0.4 on 2019-04-17 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20190417_1415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basecity',
            options={'ordering': ['-province', '-name']},
        ),
        migrations.AlterField(
            model_name='partner',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_partner', to='base.Company', verbose_name='所在公司'),
        ),
    ]
