# Generated by Django 2.0.4 on 2019-04-13 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20190413_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basecountry',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-create_time']},
        ),
        migrations.AddField(
            model_name='basecountry',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间'),
        ),
    ]
