# Generated by Django 2.0.4 on 2019-04-16 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_basesequence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basesequence',
            options={'ordering': ['-name']},
        ),
        migrations.AddField(
            model_name='basesequence',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Company', verbose_name='所属公司'),
        ),
    ]
