# Generated by Django 2.0.4 on 2019-04-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20190413_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecountry',
            name='national_flag',
            field=models.ImageField(default='country_image/national_flag.png', upload_to='country_image/', verbose_name='国旗图标'),
        ),
    ]
