# Generated by Django 2.0.4 on 2019-04-16 23:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20190416_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='partner_tags',
        ),
        migrations.AddField(
            model_name='partnertag',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='partnertag',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Partner', verbose_name='所属客户'),
        ),
        migrations.AddField(
            model_name='partnertag',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_partner_tags', to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
    ]
