# Generated by Django 2.0.4 on 2019-04-18 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20190417_2041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseunit',
            options={'ordering': ['-unit_type', '-name']},
        ),
    ]
