# Generated by Django 2.0.4 on 2019-04-17 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20190416_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='tags',
            field=models.ManyToManyField(blank=True, to='base.PartnerTag', verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='partnertag',
            name='user',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='partner_tags', to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='partnertag',
            name='partner',
        ),
        migrations.AlterUniqueTogether(
            name='partnertag',
            unique_together={('user', 'name')},
        ),
    ]
