# Generated by Django 2.0.4 on 2019-04-21 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20190421_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='parent_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_company_list', to='base.Company', verbose_name='上级公司'),
        ),
        migrations.AlterField(
            model_name='currencyrate',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_rate_list', to='base.Currency', verbose_name='所属货币'),
        ),
        migrations.AlterField(
            model_name='department',
            name='parent_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_department_list', to='base.Department', verbose_name='上级部门'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_employee_list', to='base.Department', verbose_name='所属部门'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_partner', to='base.Company', verbose_name='所在公司'),
        ),
        migrations.AlterField(
            model_name='partnertag',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_partner_tags', to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_group_list', to='base.UserGroup', verbose_name='上级用户组'),
        ),
    ]
