# Generated by Django 2.0.4 on 2019-04-14 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20190413_2256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseprovince',
            options={'ordering': ['-name']},
        ),
        migrations.AlterField(
            model_name='baseunit',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='单位'),
        ),
    ]
