# Generated by Django 2.0.4 on 2019-04-14 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20190414_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseunit',
            name='compute_type',
            field=models.CharField(choices=[('STD', '标准'), ('RIDE', '大于'), ('DIVIDE', '小于')], default='STD', max_length=255, verbose_name='计算方式'),
        ),
        migrations.AddField(
            model_name='baseunit',
            name='factor',
            field=models.CharField(default='1', max_length=255, verbose_name='比例'),
        ),
        migrations.AddField(
            model_name='baseunit',
            name='rounding',
            field=models.CharField(default='0.00', max_length=255, verbose_name='精度'),
        ),
        migrations.AddField(
            model_name='baseunit',
            name='unit_type',
            field=models.CharField(choices=[('UNIT', '数量单位'), ('WEIGHT', '质量'), ('TIME', '时间'), ('LENGTH', '长度'), ('OTHER', '其他')], default='UNIT', max_length=255, verbose_name='单位类别'),
        ),
    ]
