# Generated by Django 2.0.4 on 2019-04-14 13:38

import base.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20190414_0232'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='名称')),
                ('color', models.CharField(blank=True, max_length=255, null=True, verbose_name='颜色')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'base_partner_tag',
            },
        ),
        migrations.AlterModelOptions(
            name='baseunit',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-name']},
        ),
        migrations.RemoveField(
            model_name='company',
            name='company_type',
        ),
        migrations.RemoveField(
            model_name='company',
            name='country',
        ),
        migrations.RemoveField(
            model_name='company',
            name='legal_person',
        ),
        migrations.RemoveField(
            model_name='company',
            name='uniform_social_credit_code',
        ),
        migrations.AddField(
            model_name='company',
            name='child_cash_balance',
            field=models.CharField(default='0', max_length=255, verbose_name='实际资金余额'),
        ),
        migrations.AddField(
            model_name='company',
            name='child_dummy_balance',
            field=models.CharField(default='0', max_length=255, verbose_name='返点资金余额'),
        ),
        migrations.AddField(
            model_name='company',
            name='dummy_discount',
            field=models.CharField(default='40', max_length=255, verbose_name='默认返点比例(%)'),
        ),
        migrations.AddField(
            model_name='partner',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='详细地址'),
        ),
        migrations.AddField(
            model_name='partner',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.BaseCity', verbose_name='城市'),
        ),
        migrations.AddField(
            model_name='partner',
            name='contact_info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='联系方式'),
        ),
        migrations.AddField(
            model_name='partner',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.BaseCountry', verbose_name='所在国家'),
        ),
        migrations.AddField(
            model_name='partner',
            name='desc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='详细描述'),
        ),
        migrations.AddField(
            model_name='partner',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='合作伙伴邮箱'),
        ),
        migrations.AddField(
            model_name='partner',
            name='legal_person',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='公司法人'),
        ),
        migrations.AddField(
            model_name='partner',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=base.utils.CustomFileStorage(), unique=True, upload_to='company_logo/', verbose_name='公司Logo'),
        ),
        migrations.AddField(
            model_name='partner',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.BaseProvince', verbose_name='省份'),
        ),
        migrations.AddField(
            model_name='partner',
            name='uniform_social_credit_code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='企业统一社会信用代码(税号)'),
        ),
        migrations.AddField(
            model_name='partner',
            name='web_site',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='合作伙伴网址'),
        ),
        migrations.AddField(
            model_name='partner',
            name='partner_tags',
            field=models.ManyToManyField(blank=True, to='base.PartnerTag', verbose_name='标签'),
        ),
    ]
