# Generated by Django 2.0.4 on 2019-04-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20190414_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='register_date',
            field=models.DateField(blank=True, null=True, verbose_name='成立时间'),
        ),
    ]
