# Generated by Django 2.0.4 on 2019-04-14 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20190414_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='职位名称')),
                ('code', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='唯一编码')),
                ('desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='详细描述')),
                ('requirement', models.CharField(blank=True, max_length=255, null=True, verbose_name='技能要求')),
                ('pub_date', models.DateField(blank=True, null=True, verbose_name='发布日期')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'base_job',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='工作地址'),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_contact',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='工作联系方式'),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='工作邮箱'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='base.Department', verbose_name='所属部门'),
        ),
        migrations.AddField(
            model_name='employee',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.JobClassification', verbose_name='职位'),
        ),
    ]
