# Generated by Django 2.0.4 on 2019-04-14 14:25

import base.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20190414_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='is_active',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=base.utils.CustomFileStorage(), unique=True, upload_to='user_avatar/', verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='birth_day',
            field=models.DateField(blank=True, null=True, verbose_name='生日'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.BaseCountry', verbose_name='国籍'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='graduate_school',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='毕业院校'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='home_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='家庭住址'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='id_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='身份证'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='marital_status',
            field=models.CharField(choices=[('no', '未婚'), ('yes', '已婚')], default='no', max_length=255, verbose_name='婚姻状态'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='person_phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='个人联系号码'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='登录邮箱'),
        ),
    ]
