# Generated by Django 2.0.4 on 2019-04-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20190414_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='basetax',
            name='compute_type',
            field=models.CharField(choices=[('GROUP', '税组'), ('FIXED', '固定'), ('PERCENT', '百分比')], default='PERCENT', max_length=255, verbose_name='计算方法'),
        ),
        migrations.AddField(
            model_name='basetax',
            name='factor',
            field=models.CharField(default='13', max_length=255, verbose_name='百分比'),
        ),
        migrations.AddField(
            model_name='basetax',
            name='rounding',
            field=models.CharField(default='0.00', max_length=255, verbose_name='精度'),
        ),
        migrations.AddField(
            model_name='basetax',
            name='tax_type',
            field=models.CharField(choices=[('PERSONAL_INCOME_TAX', '个人所得税'), ('INCREMENT_TAX', '增值税'), ('OTHER', '其他')], default='INCREMENT_TAX', max_length=255, verbose_name='税类型'),
        ),
    ]
