# Generated by Django 2.0.4 on 2019-04-14 15:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_auto_20190414_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(blank=True, max_length=255, null=True, verbose_name='比率')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-create_time'],
                'get_latest_by': '-create_time',
                'db_table': 'base_currency_rate',
            },
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelOptions(
            name='jobclassification',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelOptions(
            name='partnertag',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelOptions(
            name='usergroup',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'ordering': ['-real_name']},
        ),
        migrations.AddField(
            model_name='currency',
            name='rounding',
            field=models.CharField(default='0.00', max_length=255, verbose_name='精度'),
        ),
        migrations.AddField(
            model_name='currency',
            name='symbol',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='符号'),
        ),
        migrations.AddField(
            model_name='currencyrate',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Currency', verbose_name='所属货币'),
        ),
    ]
