# Generated by Django 2.0.4 on 2019-04-17 09:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='采购单号')),
                ('origin', models.CharField(default='', max_length=255, verbose_name='源单据')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Company', verbose_name='所属公司')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Partner', verbose_name='客户')),
            ],
            options={
                'ordering': ['-create_time'],
                'db_table': 'order_purchase',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_lines', to='orders.PurchaseOrder', verbose_name='采购单')),
            ],
            options={
                'ordering': ['-create_time'],
                'db_table': 'order_purchase_line',
            },
        ),
        migrations.CreateModel(
            name='SaleOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='销售单号')),
                ('origin', models.CharField(default='', max_length=255, verbose_name='源单据')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Company', verbose_name='所属公司')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Partner', verbose_name='客户')),
            ],
            options={
                'ordering': ['-create_time'],
                'db_table': 'order_sale',
            },
        ),
        migrations.CreateModel(
            name='SaleOrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True)),
                ('sale_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_lines', to='orders.SaleOrder', verbose_name='销售单')),
            ],
            options={
                'ordering': ['-create_time'],
                'db_table': 'order_sale_line',
            },
        ),
    ]
