# Generated by Django 2.0.4 on 2019-04-16 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='saleorder',
            table='order_sale',
        ),
    ]
